yipyip small change translating the mod
Azagwen/ATBYW pull request #1
Opened 2020-12-18 19:30 UTC by takipsizad

2020-12-18 20:57 UTC, Azagwen commented
You can say it here when you are done :>

2020-12-19 06:51 UTC, takipsizad commented
it takes long time to translate all

2020-12-31 19:06 UTC, Azagwen requested changes
seems quite noticeably unfinished, even after several weeks.

2021-01-07 12:04 UTC, takipsizad commented
hey wanna look at now i translated more :)

2021-06-26 18:47 UTC, closed without merging